var res = {
    "cmm_colon": "：",
    "cmm_day": "Day",
    "cmm_time_day": "Days",
    "cmm_time_h": "H",
    "cmm_time_hours": "Hours",
    "cmm_time_month": "Month",
    "cmm_time_m": "M",
    "cmm_time_minutes": "Minutes",
    "cmm_time_s": "S",
    "cmm_time_seconds": "Seconds",
    "cmm_time_week": "Week",
    "cmm_time_year": "Year",
    "cmm_time_clock": "O'clock",
    "cmm_to": "to",
    "cmm_week_fri": "Fri",
    "cmm_week_thur": "Thur",
    "cmm_week_tues": "Tuse",
    "cmm_week_mon": "Mon",
    "cmm_week_sat": "Sat",
    "cmm_week_sun": "Sun",
    "cmm_week_wed": "Wed",
    "sch_expression": "CRON Expression",
    "sch_last_day_for_month": "on the last day of the month",
    "sch_last_day_for_weekday": "on the last weekday of the month",
    "sch_last_day": "on the last",
    "sch_on_the_day": "on the ",
    "sch_per": "Every",
    "sch_per_s": "Every seconds",
    "sch_per_m": "Every minutes",
    "sch_per_h": "Every hour",
    "sch_perform_once": "perform once",
    "sch_per_day": "every day",
    "sch_per_month": "every month",
    "sch_per_year": "every year",
    "sch_round_from": "The period is",
    "sch_start_at": " starting at ",
    "sch_specific_second": "Specific second (choose one or many)",
    "sch_specific_minute": "Specific minute (choose one or many)",
    "sch_specific_hour": "Specific hour (choose one or many)",
    "sch_specific_week": "Specific day of week (choose one or many)",
    "sch_specific_day": "Specific day of month (choose one or many)",
    "sch_specific_month": "Specific month (choose one or many)",
    "sch_specific_year": "Specific year (choose one or many)",
    "sch_the_month": "of the month",
 }
 
 export default res