var res = {
   "cmm_colon": "：",
   "cmm_day": "日",
   "cmm_time_day": "天",
   "cmm_time_h": "小时",
   "cmm_time_hours": "小时",
   "cmm_time_month": "月",
   "cmm_time_m": "分钟",
   "cmm_time_minutes": "分钟",
   "cmm_time_s": "秒",
   "cmm_time_seconds": "秒",
   "cmm_time_week": "周",
   "cmm_time_year": "年",
   "cmm_time_clock": "时",
   "cmm_to": "至",
   "cmm_week_fri": "周五",
   "cmm_week_thur": "周四",
   "cmm_week_tues": "周二",
   "cmm_week_mon": "周一",
   "cmm_week_sat": "周六",
   "cmm_week_sun": "周日",
   "cmm_week_wed": "周三",
   "sch_expression": "CRON表达式",
   "sch_last_day_for_month": "当月的最后一天",
   "sch_last_day_for_weekday": "当月的最后一个工作日",
   "sch_last_day": "当月的最后一个",
   "sch_on_the_day": "当月的第",
   "sch_per": "每",
   "sch_per_s": "每一秒钟",
   "sch_per_m": "每一分钟",
   "sch_per_h": "每一小时",
   "sch_perform_once": "执行一次",
   "sch_per_day": "每一天",
   "sch_per_month": "每一月",
   "sch_per_year": "每一年",
   "sch_round_from": "周期从",
   "sch_start_at": "执行 从",
   "sch_specific_second": "具体秒数（可多选）",
   "sch_specific_minute": "具体分钟（可多选）",
   "sch_specific_hour": "具体小时（可多选）",
   "sch_specific_week": "具体星期（可多选）",
   "sch_specific_day": "具体日期（可多选）",
   "sch_specific_month": "具体月份（可多选）",
   "sch_specific_year": "具体年份（可多选）",
   "sch_the_month": "个",
}

export default res